//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace OpenT2T { namespace Sample { namespace SuperPopular { namespace TemperatureSensor {

public interface class ITemperatureSensorService
{
public:
    // Implement this function to handle calls to the getCurrentTemperature method.
    Windows::Foundation::IAsyncOperation<TemperatureSensorGetCurrentTemperatureResult^>^ GetCurrentTemperatureAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the getTemperatureTrend method.
    Windows::Foundation::IAsyncOperation<TemperatureSensorGetTemperatureTrendResult^>^ GetTemperatureTrendAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

};

} } } } } 
