//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace OpenT2T { namespace Sample { namespace SuperPopular { namespace TemperatureSensor {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ITemperatureSensorService. Instead, TemperatureSensorServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class TemperatureSensorServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ITemperatureSensorService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<TemperatureSensorServiceEventAdapter^, TemperatureSensorGetCurrentTemperatureCalledEventArgs^>^ GetCurrentTemperatureCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<TemperatureSensorServiceEventAdapter^, TemperatureSensorGetCurrentTemperatureCalledEventArgs^>^ handler) 
        { 
            return _GetCurrentTemperatureCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<TemperatureSensorServiceEventAdapter^>(sender), safe_cast<TemperatureSensorGetCurrentTemperatureCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetCurrentTemperatureCalled -= token; 
        } 
    internal: 
        void raise(TemperatureSensorServiceEventAdapter^ sender, TemperatureSensorGetCurrentTemperatureCalledEventArgs^ args) 
        { 
            _GetCurrentTemperatureCalled(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<TemperatureSensorServiceEventAdapter^, TemperatureSensorGetTemperatureTrendCalledEventArgs^>^ GetTemperatureTrendCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<TemperatureSensorServiceEventAdapter^, TemperatureSensorGetTemperatureTrendCalledEventArgs^>^ handler) 
        { 
            return _GetTemperatureTrendCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<TemperatureSensorServiceEventAdapter^>(sender), safe_cast<TemperatureSensorGetTemperatureTrendCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _GetTemperatureTrendCalled -= token; 
        } 
    internal: 
        void raise(TemperatureSensorServiceEventAdapter^ sender, TemperatureSensorGetTemperatureTrendCalledEventArgs^ args) 
        { 
            _GetTemperatureTrendCalled(sender, args);
        } 
    }

    // Property Read Events
    // Property Write Events
    // ITemperatureSensorService Implementation
    virtual Windows::Foundation::IAsyncOperation<TemperatureSensorGetCurrentTemperatureResult^>^ GetCurrentTemperatureAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<TemperatureSensorGetTemperatureTrendResult^>^ GetTemperatureTrendAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);



private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetCurrentTemperatureCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _GetTemperatureTrendCalled;
};

} } } } } 
