//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#include "pch.h"

using namespace Microsoft::WRL;
using namespace Platform;
using namespace Windows::Devices::AllJoyn;
using namespace Windows::Foundation;
using namespace org::OpenT2T::Sample::SuperPopular::TemperatureSensor;

void TemperatureSensorSignals::Initialize(_In_ alljoyn_busobject busObject, _In_ alljoyn_sessionid sessionId)
{
    m_busObject = busObject;
    m_sessionId = sessionId;

    auto interfaceDefinition = alljoyn_busattachment_getinterface(alljoyn_busobject_getbusattachment(busObject), "org.OpenT2T.Sample.SuperPopular.TemperatureSensor");
    alljoyn_interfacedescription_getmember(interfaceDefinition, "error", &m_memberError);
}

void TemperatureSensorSignals::Error(_In_ Platform::String^ interfaceMemberType, _In_ Platform::String^ interfaceMemberMessage)
{
    if (nullptr == m_busObject)
    {
        return;
    }

    size_t argCount = 2;
    alljoyn_msgarg arguments = alljoyn_msgarg_array_create(argCount);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 0), "s", interfaceMemberType);
    (void)TypeConversionHelpers::SetAllJoynMessageArg(alljoyn_msgarg_array_element(arguments, 1), "s", interfaceMemberMessage);
    
    alljoyn_busobject_signal(
        m_busObject, 
        NULL,  // Generated code only supports broadcast signals.
        m_sessionId,
        m_memberError,
        arguments,
        argCount, 
        0, // A signal with a TTL of 0 will be sent to every member of the session, regardless of how long it takes to deliver the message
        ALLJOYN_MESSAGE_FLAG_GLOBAL_BROADCAST, // Broadcast to everyone in the session.
        NULL); // The generated code does not need the generated signal message

    alljoyn_msgarg_destroy(arguments);
}

void TemperatureSensorSignals::CallErrorReceived(_In_ TemperatureSensorSignals^ sender, _In_ TemperatureSensorErrorReceivedEventArgs^ args)
{
    ErrorReceived(sender, args);
}

