//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace OpenT2T { namespace Sample { namespace SuperPopular { namespace TemperatureSensor {

// Methods
public ref class TemperatureSensorGetCurrentTemperatureCalledEventArgs sealed
{
public:
    TemperatureSensorGetCurrentTemperatureCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property TemperatureSensorGetCurrentTemperatureResult^ Result
    {
        TemperatureSensorGetCurrentTemperatureResult^ get() { return m_result; }
        void set(_In_ TemperatureSensorGetCurrentTemperatureResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<TemperatureSensorGetCurrentTemperatureResult^>^ GetResultAsync(TemperatureSensorGetCurrentTemperatureCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<TemperatureSensorGetCurrentTemperatureResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<TemperatureSensorGetCurrentTemperatureResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    TemperatureSensorGetCurrentTemperatureResult^ m_result;
};

public ref class TemperatureSensorGetTemperatureTrendCalledEventArgs sealed
{
public:
    TemperatureSensorGetTemperatureTrendCalledEventArgs(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);

    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
    }

    property TemperatureSensorGetTemperatureTrendResult^ Result
    {
        TemperatureSensorGetTemperatureTrendResult^ get() { return m_result; }
        void set(_In_ TemperatureSensorGetTemperatureTrendResult^ value) { m_result = value; }
    }

    Windows::Foundation::Deferral^ GetDeferral();

    static Windows::Foundation::IAsyncOperation<TemperatureSensorGetTemperatureTrendResult^>^ GetResultAsync(TemperatureSensorGetTemperatureTrendCalledEventArgs^ args)
    {
        args->InvokeAllFinished();
        auto t = concurrency::create_task(args->m_tce);
        return concurrency::create_async([t]() -> concurrency::task<TemperatureSensorGetTemperatureTrendResult^>
        {
            return t;
        });
    }
    
private:
    void Complete();
    void InvokeAllFinished();
    void InvokeCompleteHandler();

    bool m_raised;
    int m_completionsRequired;
    concurrency::task_completion_event<TemperatureSensorGetTemperatureTrendResult^> m_tce;
    std::mutex m_lock;
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;
    TemperatureSensorGetTemperatureTrendResult^ m_result;
};

// Readable Properties
// Writable Properties
} } } } } 
