//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace OpenT2T { namespace Sample { namespace SuperPopular { namespace TemperatureSensor {

// Signals
public ref class TemperatureSensorErrorReceivedEventArgs sealed
{
public:
    property Windows::Devices::AllJoyn::AllJoynMessageInfo^ MessageInfo
    {
        Windows::Devices::AllJoyn::AllJoynMessageInfo^ get() { return m_messageInfo; }
        void set(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ value) { m_messageInfo = value; }
    }

    property Platform::String^ Type
    {
        Platform::String^ get() { return m_interfaceMemberType; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberType = value; }
    }
    property Platform::String^ Message
    {
        Platform::String^ get() { return m_interfaceMemberMessage; }
    internal:
        void set(_In_ Platform::String^ value) { m_interfaceMemberMessage = value; }
    }

private:
    Windows::Devices::AllJoyn::AllJoynMessageInfo^ m_messageInfo;

    Platform::String^ m_interfaceMemberType;
    Platform::String^ m_interfaceMemberMessage;
};


} } } } } 
