//-----------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
//
//   For more information, see: http://go.microsoft.com/fwlink/?LinkID=623246
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace OpenT2T { namespace Sample { namespace SuperPopular { namespace Lamp {

public interface class ILampService
{
public:
    // Implement this function to handle calls to the turnOn method.
    Windows::Foundation::IAsyncOperation<LampTurnOnResult^>^ TurnOnAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the turnOff method.
    Windows::Foundation::IAsyncOperation<LampTurnOffResult^>^ TurnOffAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info );

    // Implement this function to handle calls to the setBrightness method.
    Windows::Foundation::IAsyncOperation<LampSetBrightnessResult^>^ SetBrightnessAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info , _In_ uint32 interfaceMemberBrightness);

};

} } } } } 
