//-----------------------------------------------------------------------------
// <auto-generated> 
//   This code was generated by a tool. 
// 
//   Changes to this file may cause incorrect behavior and will be lost if  
//   the code is regenerated.
//
//   Tool: AllJoynCodeGenerator.exe
//
//   This tool is located in the Windows 10 SDK and the Windows 10 AllJoyn 
//   Visual Studio Extension in the Visual Studio Gallery.  
//
//   The generated code should be packaged in a Windows 10 C++/CX Runtime  
//   Component which can be consumed in any UWP-supported language using 
//   APIs that are available in Windows.Devices.AllJoyn.
//
//   Using AllJoynCodeGenerator - Invoke the following command with a valid 
//   Introspection XML file and a writable output directory:
//     AllJoynCodeGenerator -i <INPUT XML FILE> -o <OUTPUT DIRECTORY>
// </auto-generated>
//-----------------------------------------------------------------------------
#pragma once

namespace org { namespace OpenT2T { namespace Sample { namespace SuperPopular { namespace Lamp {

// This class, and the associated EventArgs classes, exist for the benefit of JavaScript developers who
// do not have the ability to implement ILampService. Instead, LampServiceEventAdapter
// provides the Interface implementation and exposes a set of compatible events to the developer.
public ref class LampServiceEventAdapter sealed : [Windows::Foundation::Metadata::Default] ILampService
{
public:
    // Method Invocation Events
    event Windows::Foundation::TypedEventHandler<LampServiceEventAdapter^, LampTurnOnCalledEventArgs^>^ TurnOnCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<LampServiceEventAdapter^, LampTurnOnCalledEventArgs^>^ handler) 
        { 
            return _TurnOnCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<LampServiceEventAdapter^>(sender), safe_cast<LampTurnOnCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _TurnOnCalled -= token; 
        } 
    internal: 
        void raise(LampServiceEventAdapter^ sender, LampTurnOnCalledEventArgs^ args) 
        { 
            _TurnOnCalled(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<LampServiceEventAdapter^, LampTurnOffCalledEventArgs^>^ TurnOffCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<LampServiceEventAdapter^, LampTurnOffCalledEventArgs^>^ handler) 
        { 
            return _TurnOffCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<LampServiceEventAdapter^>(sender), safe_cast<LampTurnOffCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _TurnOffCalled -= token; 
        } 
    internal: 
        void raise(LampServiceEventAdapter^ sender, LampTurnOffCalledEventArgs^ args) 
        { 
            _TurnOffCalled(sender, args);
        } 
    }

    event Windows::Foundation::TypedEventHandler<LampServiceEventAdapter^, LampSetBrightnessCalledEventArgs^>^ SetBrightnessCalled 
    { 
        Windows::Foundation::EventRegistrationToken add(Windows::Foundation::TypedEventHandler<LampServiceEventAdapter^, LampSetBrightnessCalledEventArgs^>^ handler) 
        { 
            return _SetBrightnessCalled += ref new Windows::Foundation::EventHandler<Platform::Object^>
            ([handler](Platform::Object^ sender, Platform::Object^ args)
            {
                handler->Invoke(safe_cast<LampServiceEventAdapter^>(sender), safe_cast<LampSetBrightnessCalledEventArgs^>(args));
            }, Platform::CallbackContext::Same);
        } 
        void remove(Windows::Foundation::EventRegistrationToken token) 
        { 
            _SetBrightnessCalled -= token; 
        } 
    internal: 
        void raise(LampServiceEventAdapter^ sender, LampSetBrightnessCalledEventArgs^ args) 
        { 
            _SetBrightnessCalled(sender, args);
        } 
    }

    // Property Read Events
    // Property Write Events
    // ILampService Implementation
    virtual Windows::Foundation::IAsyncOperation<LampTurnOnResult^>^ TurnOnAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampTurnOffResult^>^ TurnOffAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info);
    virtual Windows::Foundation::IAsyncOperation<LampSetBrightnessResult^>^ SetBrightnessAsync(_In_ Windows::Devices::AllJoyn::AllJoynMessageInfo^ info, _In_ uint32 interfaceMemberBrightness);



private:
    event Windows::Foundation::EventHandler<Platform::Object^>^ _TurnOnCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _TurnOffCalled;
    event Windows::Foundation::EventHandler<Platform::Object^>^ _SetBrightnessCalled;
};

} } } } } 
